# Configuration file for the duration of DHCP leases

# Global variable
Globale:
  lease: '600'          # Duration by default of leases in seconds
  lease_max: '7200'     # Maximum duration of leases in seconds
