# configuration des VLANs

VLAN1:
  num: '1'
  bootproto: 'static'
  adresse: '192.168.5.2'
  netmask: '255.255.255.0'
  network: '192.168.5.0'
  gateway: ''                  # Optional
  interface: 'enp0s3'          # Physical interface