# Configuring network adapters

# Network adaptater #1
Carte1:
  adresse: '192.168.0.1'
  reseau: '192.168.0.0'
  broadcast: '192.168.0.255'
  netmask: '255.255.255.0'
  gateway: ''                 # ONLY ONE GATEWAY (it's the default gateway)
  mode: 'static'
  name: 'enp0s3'
  type: 'Ethernet'
  cidr: '24'
  primaire: 'y'                # Specify if this is the main interface (y -> yes    n -> no). Only one card can be main !!!!

# Network adaptater #1
Carte2:
  adresse: '192.168.0.2'
  reseau: '192.168.0.0'
  broadcast: '192.168.0.255'
  netmask: '255.255.255.0'
  gateway: ''
  mode: 'static'
  name: 'enp0s8'
  type: 'Ethernet'
  cidr: '24'
  primaire: 'n'                # Specify if this is the main interface (y -> yes    n -> no). Only one card can be main !!!!

# Network adaptater #1
Carte3:
  adresse: '192.168.0.3'
  reseau: '192.168.0.0'
  broadcast: '192.168.0.255'
  netmask: '255.255.255.0'
  gateway: '192.168.0.254'
  mode: 'static'
  name: 'enp0s9'
  type: 'Ethernet'
  cidr: '24'
  primaire: 'n'                # Specify if this is the main interface (y -> yes    n -> no). Only one card can be main !!!!
